plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/yarn-plugin-nixify.cjs
    spec: "https://raw.githubusercontent.com/stephank/yarn-plugin-nixify/main/dist/yarn-plugin-nixify.js"
  - path: .yarn/plugins/@yarnpkg/plugin-production-install.cjs
    spec: "https://gitlab.com/Larry1123/yarn-contrib/-/raw/master/packages/plugin-production-install/bundles/@yarnpkg/plugin-production-install.js"

yarnPath: .yarn/releases/yarn-berry.cjs

packageExtensions:
  eslint-module-utils@*:
    dependencies:
      eslint: "*"
      "@typescript-eslint/parser": "*"
      eslint-import-resolver-node: "*"

# yarn-plugin-nixify
generateDefaultNix: false
