name: Tests

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  tests:
    defaults:
      run:
        shell: nix-shell --run "/bin/bash -e {0}"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: cachix/install-nix-action@v12
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Set up environment
        run: |
          yarn install --immutable

      # TODO: We can use the custom foreach command to only build/lint/test changed workspaces
      - name: Build
        run: |
          yarn workspaces foreach -vApt run build
      - name: Lint
        run: |
          yarn workspaces foreach -vAp run lint
      - name: Test
        run: |
          yarn workspaces foreach -vAp run test
